### PR TITLE
Move lsif-util code to lsif-node

### PR DESCRIPTION
**Pull request by jumattos**
This pull request moves all code from [lsif-util](https://github.com/jumattos/lsif-util) to lsif-node.

### CODE REVIEW

**Comment by dbaeumer** [comment]
Thanks for the PR. A couple of comments:

- the files need to have a copyright statement. 
```
/* --------------------------------------------------------------------------------------------
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 * ------------------------------------------------------------------------------------------ */
```
- why do we need the `tslint-microsoft-contrib`. In general we avoid having unnecessary dependency. It looks most rules are configures to be `false` anyways
- we need to agree on `yargs` versus `minimist`. I quickly looked at `yargs` and it seems to be more suitable for what we want to do. What are your experiences.
- whenever possible you should avoid `process.exit()`. If you want to set a return code use `process.exitCode` and let the process exit normally.

**Comment by jumattos** [comment]
Changes made so far:
- Copyright statement added to each file
- `tslint-microsoft-contrib` removed
- Couple of rules added to `tslint.json`
- Lint fixes
- `process.exit()` replaced by `process.exitCode`

**Comment by jumattos** [comment]
About the `yargs` vs `minimist` discussion: until now yargs has met all of my needs. I find it easy to define commands and options using the API and I appreciate the automatically generated "help" text:

```
Usage: main.js [validate|visualize] [file] --inputFormat=[line|json] [filters]

Commands:
  main.js validate [file]
  main.js visualize [file]

Options:
  --version      Show version number                                   [boolean]
  --inputFormat  Specify input format[choices: "line", "json"] [default: "line"]
  --id           Filter by id                              [array] [default: []]
  --inV          Filter by inV                             [array] [default: []]
  --outV         Filter by outV                            [array] [default: []]
  --type         Filter by type                            [array] [default: []]
  --label        Filter by label                           [array] [default: []]
  --property     Filter by property                        [array] [default: []]
  --regex        Filter by regex                                        [string]
  --info         Show usage information                                [boolean]
```

From the quick glance I gave at minimist, it doesn't seem to offer as many features, but I will take a more careful look.

**Comment by jumattos** [comment]
@dbaeumer and @arjun27:
Should we default to stdin if no file is specified? Currently in order to pipe LSIF output we have to use the `--stdin` flag like so:
> lsif-tsc -p .\tsconfig.json | lsif-util validate --stdin

The experience could be a bit more similar to the lsif-npm tool if we drop the `--stdin` flag. It seems like the right thing to do, but I wanted to check with you first.

**Comment by jumattos** [comment]
I took the liberty to add an extra step to the CI to run my unit tests. This repository as a whole could benefit from more testing.

We should consider using the `lsif-util validation` to test the `lsif-tsc` tool.

**Comment by dbaeumer** [comment]
@jumattos thanks for the update. Just wanted to let you know that I am busy heads down for LSIF 0.4 (the cluster changes) and this needs to wait until mid next week. Sorry.

So comments regardind --stdin when in pipe mode: what would be super cool is if we can detect that the second tool is actually running in a pipe. Then I would argue we should automatically read from stdin. However making this the default all the time had the bad side effect that the tools started but without any input from stdin simply waited with a blinking cursor without any indication to the user what is wrong.

**Comment by jumattos** [comment]
Right now if the user tries to do the following:
> lsif-util validate
we throw an error since we can't find the default input file (`lsif.json`).

I am going to change that so that it asks for a file (dropping the default) and suggests using `--stdin` if pipelining.

It's actually good that you won't review it now, since it will give me time to fix that experience. I will ping you regardless once this PR is ready for a final review, just to keep you informed. Thanks!

**Comment by jumattos** [comment]
@dbaeumer This PR is ready for another review! I removed the default value of the input path. This is what happens when the user does not provide one:

``` bash
> node .\lib\main.js visualize
main.js visualize [file]

Positionals:
  file  Path to input file or --stdin

Options:
  --version      Show version number                                   [boolean]
  --inputFormat  Specify input format[choices: "line", "json"] [default: "line"]
  --id           Filter by id                              [array] [default: []]
  --inV          Filter by inV                             [array] [default: []]
  --outV         Filter by outV                            [array] [default: []]
  --type         Filter by type                            [array] [default: []]
  --label        Filter by label                           [array] [default: []]
  --property     Filter by property                        [array] [default: []]
  --regex        Filter by regex                                        [string]
  --info         Show usage information                                [boolean]
  --distance     Max distance between any vertex and the filtered input
                                                                    [default: 1]

Error: Missing input file. Did you forget --stdin?
```

Bumped the version to 1.0.0 since this is a breaking change (not that I expect anyone to be using this default value).

**Pull request merged**
